export const App = {
  SET_CURRENT: 'APP_SET_CURRENT'
}

export const MasterAdmin = {
  CONTEXTS_LIST_REQUEST: 'CONTEXTS_LIST_REQUEST',
  CONTEXTS_LIST_SUCCESS: 'CONTEXTS_LIST_SUCCESS',
  CONTEXTS_LIST_ERROR: 'CONTEXTS_LIST_ERROR'
}
