export const App = {
  SET_CURRENT: 'SET_CURRENT',
  ENDPOINTS_LIST_REQUEST: 'ENDPOINTS_LIST_REQUEST',
  ENDPOINTS_LIST_SUCCESS: 'ENDPOINTS_LIST_SUCCESS',
  ENDPOINTS_LIST_ERROR: 'ENDPOINTS_LIST_ERROR'
}

export const MasterAdmin = {
  CONTEXTS_LIST_REQUEST: 'CONTEXTS_LIST_REQUEST',
  CONTEXTS_LIST_SUCCESS: 'CONTEXTX_LIST_SUCCESS',
  CONTEXTS_LIST_ERROR: 'CONTEXTS_LIST_ERROR',
  CONTEXT_CREATE_REQUEST: 'CONTEXT_CREATE_REQUEST',
  CONTEXT_CREATE_SUCCESS: 'CONTEXT_CREATE_SUCCESS',
  CONTEXT_CREATE_ERROR: 'CONTEXT_CREATE_ERROR',
  CONTEXT_UPDATE_REQUEST: 'CONTEXT_UPDATE_REQUEST',
  CONTEXT_UPDATE_SUCCESS: 'CONTEXT_UPDATE_SUCCESS',
  CONTEXT_UPDATE_ERROR: 'CONTEXT_UPDATE_ERROR',
  CONTEXT_DELETE_REQUEST: 'CONTEXT_DELETE_REQUEST',
  CONTEXT_DELETE_SUCCESS: 'CONTEXT_DELETE_SUCCESS',
  CONTEXT_DELETE_ERROR: 'CONTEXT_DELETE_ERROR',
  CONTEXT_ERROR_RESET: 'CONTEXT_ERROR_RESET',
  SET_ENDPOINT: 'SET_ENDPOINT',
  SESSION_CREATE_REQUEST: 'SESSION_CREATE_REQUEST',
  SESSION_CREATE_SUCCESS: 'SESSION_CREATE_SUCCESS',
  SESSION_CREATE_ERROR: 'SESSION_CREATE_ERROR',
  SESSION_GET_REQUEST: 'SESSION_GET_REQUEST',
  SESSION_GET_SUCCESS: 'SESSION_GET_SUCCESS',
  SESSION_GET_ERROR: 'SESSION_GET_ERROR',
  SESSION_DELETE_REQUEST: 'SESSION_DELETE_REQUEST',
  SESSION_DELETE_SUCCESS: 'SESSION_DELETE_SUCCESS',
  SESSION_DELETE_ERROR: 'SESSION_DELETE_ERROR'
}

export const ContextAdmin = {
  SESSION_CREATE_REQUEST: 'SESSION_CREATE_REQUEST',
  SESSION_CREATE_SUCCESS: 'SESSION_CREATE_SUCCESS',
  SESSION_CREATE_ERROR: 'SESSION_CREATE_ERROR',
  SESSION_GET_REQUEST: 'SESSION_GET_REQUEST',
  SESSION_GET_SUCCESS: 'SESSION_GET_SUCCESS',
  SESSION_GET_ERROR: 'SESSION_GET_ERROR',
  SESSION_DELETE_REQUEST: 'SESSION_DELETE_REQUEST',
  SESSION_DELETE_SUCCESS: 'SESSION_DELETE_SUCCESS',
  SESSION_DELETE_ERROR: 'SESSION_DELETE_ERROR'
}
