export const App = {
  SET_CURRENT: 'SET_CURRENT',
  GET_CURRENT: 'GET_CURRENT',
  ENDPOINTS_LIST_REQUEST: 'ENDPOINTS_LIST_REQUEST',
  ENDPOINTS_LIST_SUCCESS: 'ENDPOINTS_LIST_SUCCESS',
  ENDPOINTS_LIST_ERROR: 'ENDPOINTS_LIST_ERROR',
  SESSION_CREATE_REQUEST: 'SESSION_CREATE_REQUEST',
  SESSION_CREATE_SUCCESS: 'SESSION_CREATE_SUCCESS',
  SESSION_CREATE_ERROR: 'SESSION_CREATE_ERROR',
  SESSION_GET_REQUEST: 'SESSION_GET_REQUEST',
  SESSION_GET_SUCCESS: 'SESSION_GET_SUCCESS',
  SESSION_GET_ERROR: 'SESSION_GET_ERROR',
  SESSION_DELETE_REQUEST: 'SESSION_DELETE_REQUEST',
  SESSION_DELETE_SUCCESS: 'SESSION_DELETE_SUCCESS',
  SESSION_DELETE_ERROR: 'SESSION_DELETE_ERROR',
  SESSION_SET_FOR_APP: 'SESSION_SET_FOR_APP'
}

export const MasterAdmin = {
  CONTEXTS_LIST_REQUEST: 'CONTEXTS_LIST_REQUEST',
  CONTEXTS_LIST_SUCCESS: 'CONTEXTX_LIST_SUCCESS',
  CONTEXTS_LIST_ERROR: 'CONTEXTS_LIST_ERROR'
}
