# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.context import Context  # noqa: F401,E501
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class ContextCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, context: Context=None, user: User=None):
        """ContextCreate - a model defined in Swagger

        :param context: The context of this ContextCreate.
        :type context: Context
        :param user: The user of this ContextCreate.
        :type user: User
        """
        self.swagger_types = {
            'context': Context,
            'user': User
        }

        self.attribute_map = {
            'context': 'context',
            'user': 'user'
        }

        self._context = context
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'ContextCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ContextCreate of this ContextCreate.
        :rtype: ContextCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self) -> Context:
        """Gets the context of this ContextCreate.

        The context information

        :return: The context of this ContextCreate.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this ContextCreate.

        The context information

        :param context: The context of this ContextCreate.
        :type context: Context
        """
        if context is None:
            raise ValueError("Invalid value for `context`, must not be `None`")

        self._context = context

    @property
    def user(self) -> User:
        """Gets the user of this ContextCreate.

        The admin user information of a context

        :return: The user of this ContextCreate.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user: User):
        """Sets the user of this ContextCreate.

        The admin user information of a context

        :param user: The user of this ContextCreate.
        :type user: User
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")

        self._user = user
