# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse200(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, oxap_account_id: str=None, oxap_account_name: str=None, oxap_account_description: str=None, endpoint_id: str=None, endpoint_name: str=None, endpoint_description: str=None):
        """
        InlineResponse200 - a model defined in Swagger

        :param oxap_account_id: The oxap_account_id of this InlineResponse200.
        :type oxap_account_id: str
        :param oxap_account_name: The oxap_account_name of this InlineResponse200.
        :type oxap_account_name: str
        :param oxap_account_description: The oxap_account_description of this InlineResponse200.
        :type oxap_account_description: str
        :param endpoint_id: The endpoint_id of this InlineResponse200.
        :type endpoint_id: str
        :param endpoint_name: The endpoint_name of this InlineResponse200.
        :type endpoint_name: str
        :param endpoint_description: The endpoint_description of this InlineResponse200.
        :type endpoint_description: str
        """
        self.swagger_types = {
            'oxap_account_id': str,
            'oxap_account_name': str,
            'oxap_account_description': str,
            'endpoint_id': str,
            'endpoint_name': str,
            'endpoint_description': str
        }

        self.attribute_map = {
            'oxap_account_id': 'oxap_account_id',
            'oxap_account_name': 'oxap_account_name',
            'oxap_account_description': 'oxap_account_description',
            'endpoint_id': 'endpoint_id',
            'endpoint_name': 'endpoint_name',
            'endpoint_description': 'endpoint_description'
        }

        self._oxap_account_id = oxap_account_id
        self._oxap_account_name = oxap_account_name
        self._oxap_account_description = oxap_account_description
        self._endpoint_id = endpoint_id
        self._endpoint_name = endpoint_name
        self._endpoint_description = endpoint_description

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.
        :rtype: InlineResponse200
        """
        return deserialize_model(dikt, cls)

    @property
    def oxap_account_id(self) -> str:
        """
        Gets the oxap_account_id of this InlineResponse200.
        

        :return: The oxap_account_id of this InlineResponse200.
        :rtype: str
        """
        return self._oxap_account_id

    @oxap_account_id.setter
    def oxap_account_id(self, oxap_account_id: str):
        """
        Sets the oxap_account_id of this InlineResponse200.
        

        :param oxap_account_id: The oxap_account_id of this InlineResponse200.
        :type oxap_account_id: str
        """

        self._oxap_account_id = oxap_account_id

    @property
    def oxap_account_name(self) -> str:
        """
        Gets the oxap_account_name of this InlineResponse200.
        

        :return: The oxap_account_name of this InlineResponse200.
        :rtype: str
        """
        return self._oxap_account_name

    @oxap_account_name.setter
    def oxap_account_name(self, oxap_account_name: str):
        """
        Sets the oxap_account_name of this InlineResponse200.
        

        :param oxap_account_name: The oxap_account_name of this InlineResponse200.
        :type oxap_account_name: str
        """

        self._oxap_account_name = oxap_account_name

    @property
    def oxap_account_description(self) -> str:
        """
        Gets the oxap_account_description of this InlineResponse200.
        

        :return: The oxap_account_description of this InlineResponse200.
        :rtype: str
        """
        return self._oxap_account_description

    @oxap_account_description.setter
    def oxap_account_description(self, oxap_account_description: str):
        """
        Sets the oxap_account_description of this InlineResponse200.
        

        :param oxap_account_description: The oxap_account_description of this InlineResponse200.
        :type oxap_account_description: str
        """

        self._oxap_account_description = oxap_account_description

    @property
    def endpoint_id(self) -> str:
        """
        Gets the endpoint_id of this InlineResponse200.
        

        :return: The endpoint_id of this InlineResponse200.
        :rtype: str
        """
        return self._endpoint_id

    @endpoint_id.setter
    def endpoint_id(self, endpoint_id: str):
        """
        Sets the endpoint_id of this InlineResponse200.
        

        :param endpoint_id: The endpoint_id of this InlineResponse200.
        :type endpoint_id: str
        """

        self._endpoint_id = endpoint_id

    @property
    def endpoint_name(self) -> str:
        """
        Gets the endpoint_name of this InlineResponse200.
        

        :return: The endpoint_name of this InlineResponse200.
        :rtype: str
        """
        return self._endpoint_name

    @endpoint_name.setter
    def endpoint_name(self, endpoint_name: str):
        """
        Sets the endpoint_name of this InlineResponse200.
        

        :param endpoint_name: The endpoint_name of this InlineResponse200.
        :type endpoint_name: str
        """

        self._endpoint_name = endpoint_name

    @property
    def endpoint_description(self) -> str:
        """
        Gets the endpoint_description of this InlineResponse200.
        

        :return: The endpoint_description of this InlineResponse200.
        :rtype: str
        """
        return self._endpoint_description

    @endpoint_description.setter
    def endpoint_description(self, endpoint_description: str):
        """
        Sets the endpoint_description of this InlineResponse200.
        

        :param endpoint_description: The endpoint_description of this InlineResponse200.
        :type endpoint_description: str
        """

        self._endpoint_description = endpoint_description

