# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OXAPAccount(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, description: str=None):
        """OXAPAccount - a model defined in Swagger

        :param id: The id of this OXAPAccount.
        :type id: str
        :param name: The name of this OXAPAccount.
        :type name: str
        :param description: The description of this OXAPAccount.
        :type description: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description'
        }

        self._id = id
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'OXAPAccount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OXAPAccount of this OXAPAccount.
        :rtype: OXAPAccount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this OXAPAccount.

        

        :return: The id of this OXAPAccount.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this OXAPAccount.

        

        :param id: The id of this OXAPAccount.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this OXAPAccount.

        

        :return: The name of this OXAPAccount.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this OXAPAccount.

        

        :param name: The name of this OXAPAccount.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this OXAPAccount.

        

        :return: The description of this OXAPAccount.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this OXAPAccount.

        

        :param description: The description of this OXAPAccount.
        :type description: str
        """

        self._description = description
