# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.soap_map_entry import SOAPMapEntry  # noqa: F401,E501
from swagger_server import util


class SOAPStringMapMap(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, entries: List[SOAPMapEntry]=None):
        """SOAPStringMapMap - a model defined in Swagger

        :param entries: The entries of this SOAPStringMapMap.
        :type entries: List[SOAPMapEntry]
        """
        self.swagger_types = {
            'entries': List[SOAPMapEntry]
        }

        self.attribute_map = {
            'entries': 'entries'
        }

        self._entries = entries

    @classmethod
    def from_dict(cls, dikt) -> 'SOAPStringMapMap':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SOAPStringMapMap of this SOAPStringMapMap.
        :rtype: SOAPStringMapMap
        """
        return util.deserialize_model(dikt, cls)

    @property
    def entries(self) -> List[SOAPMapEntry]:
        """Gets the entries of this SOAPStringMapMap.


        :return: The entries of this SOAPStringMapMap.
        :rtype: List[SOAPMapEntry]
        """
        return self._entries

    @entries.setter
    def entries(self, entries: List[SOAPMapEntry]):
        """Sets the entries of this SOAPStringMapMap.


        :param entries: The entries of this SOAPStringMapMap.
        :type entries: List[SOAPMapEntry]
        """
        if entries is None:
            raise ValueError("Invalid value for `entries`, must not be `None`")

        self._entries = entries
