# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class StringMapMap(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, entries: object=None):
        """
        StringMapMap - a model defined in Swagger

        :param entries: The entries of this StringMapMap.
        :type entries: object
        """
        self.swagger_types = {
            'entries': object
        }

        self.attribute_map = {
            'entries': 'entries'
        }

        self._entries = entries

    @classmethod
    def from_dict(cls, dikt) -> 'StringMapMap':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StringMapMap of this StringMapMap.
        :rtype: StringMapMap
        """
        return deserialize_model(dikt, cls)

    @property
    def entries(self) -> object:
        """
        Gets the entries of this StringMapMap.
        

        :return: The entries of this StringMapMap.
        :rtype: object
        """
        return self._entries

    @entries.setter
    def entries(self, entries: object):
        """
        Sets the entries of this StringMapMap.
        

        :param entries: The entries of this StringMapMap.
        :type entries: object
        """

        self._entries = entries

