- name: enable apache service
  service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"
  tags:
    - configuration
    - apache_configuration

- name: enable httpd service
  service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"
  tags:
    - configuration
    - apache_configuration
